name: OnilineBookStore CI

on: [push]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.war staging

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
       name: onlinebookstore
       path: staging
       
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: onlinebookstore

      - name: Test the arifacts
        run: ls -R

      - name: archieve artifacts
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'onlinebookstore.zip'

      - name: Create a release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.run_number}} 
          title: Release ${{ github.ref }}
          

