name: Deploy onlinebookstore

on:
  workflow_run:
    workflows: ["Build, Test, and Package"]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-webapp
          path: artifacts

      - name: Deploy to Tomcat (example)
        # Replace this with your deployment steps, e.g., copying the .war file to a Tomcat directory or deploying to a container.
        run: |
          cp artifacts/*.war /path/to/tomcat/webapps/
